---
name: Image Building and Deployment

on:
  release:
    types: [published]
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:

  build-and-push:
    name: Build & push image
    runs-on: self-hosted

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3

      - name: Get image tag from reference context
        run: echo ${{ github.ref }} | sed -e 's/refs\/tags\//TAG=/' >> $GITHUB_ENV

      - name: Kaniko builder
        uses: aevea/action-kaniko@v0.9.0
        with:
          registry: registry.idener.es
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
          build_file: Dockerfile.mini
          image: external-dns-tests
          tag: ${{ env.TAG }}
          tag_with_latest: true
          strip_tag_prefix: v